export const mockArticles = [
  {
    id: 'a-1',
    type: 'article',
    status: 'published',
    title: 'Getting Started with Trading Basics',
    slug: 'getting-started-trading-basics',
    excerpt: 'Understand markets, orders, and key terminology before you place your first trade.',
    content: 'This is a comprehensive introduction to trading basics covering market types, order types, and essential risk management concepts.',
    tags: ['trading-basics'],
    featured_image_url: 'https://images.unsplash.com/photo-1543286386-2e659306cd6c?q=80&w=1200&auto=format&fit=crop',
    is_premium: false,
    metadata: {},
    author_id: 'u1',
    author: { id: 'u1', full_name: 'Admin', email: 'admin@example.com', membership_type: 'premium', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
  },
  {
    id: 'a-2',
    type: 'article',
    status: 'published',
    title: 'Technical Analysis: Support and Resistance',
    slug: 'technical-analysis-support-resistance',
    excerpt: 'Learn how to identify support and resistance zones and trade around them.',
    content: 'Support and resistance form the bedrock of technical analysis. In this article we explore identification, confirmation, and trading tactics.',
    tags: ['technical-analysis', 'strategies'],
    featured_image_url: 'https://images.unsplash.com/photo-1551281044-8f785ba67e45?q=80&w=1200&auto=format&fit=crop',
    is_premium: false,
    metadata: {},
    author_id: 'u1',
    author: { id: 'u1', full_name: 'Admin', email: 'admin@example.com', membership_type: 'premium', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
  },
];

export const mockLessons = [
  {
    id: 'l-1',
    type: 'lesson',
    status: 'published',
    title: 'Beginner Lesson: Candlestick Basics',
    slug: 'lesson-candlestick-basics',
    excerpt: 'Master the anatomy of candlesticks and the story they tell.',
    content: 'Candlestick charts are a trader’s language. This lesson covers bodies, wicks, and common patterns.',
    tags: ['technical-analysis', 'trading-basics'],
    featured_image_url: '',
    is_premium: false,
    metadata: { level: 'beginner', duration: '12 min' },
    author_id: 'u1',
    author: { id: 'u1', full_name: 'Coach', email: 'coach@example.com', membership_type: 'premium', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
  },
  {
    id: 'l-2',
    type: 'lesson',
    status: 'published',
    title: 'Advanced Risk Management Techniques',
    slug: 'lesson-advanced-risk-management',
    excerpt: 'Position sizing, expectancy, and portfolio-level risk control.',
    content: 'We go beyond stop-losses into Kelly criterion intuition, volatility targeting, and drawdown control.',
    tags: ['risk-management', 'advanced'],
    featured_image_url: '',
    is_premium: true,
    metadata: { level: 'advanced', duration: '18 min' },
    author_id: 'u2',
    author: { id: 'u2', full_name: 'Pro Trader', email: 'pro@example.com', membership_type: 'premium', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
  },
];

// Removed: mockSignals (signals feature deprecated)